### ISSUE TITLE
Missing tags for releases 0.1.2 through 0.1.4

### ISSUE THREAD

**Issue by bgilbert** [coreos/openat-ext#1]
There are no Git tags for current releases, and the commit history doesn't make it completely clear which commits correspond to 0.1.2 and 0.1.3.

**Comment by cgwalters** [comment]
There is a tag for the current release (0.1.6) right?  Was there something you saw missing?

I agree the git history is missing some tags but I'm not sure it's worth trying to retroactively fix versus ensuring we (I) follow a SOP for releases in the future.

**Comment by bgilbert** [comment]
There are tags for 0.1.5 and 0.1.6, which were created after I filed this issue, but 0.1.[234] are missing.  It generally seems suspicious whenever binary repos have a versioned release that doesn't exist in the upstream source tree.

Now that there are newer releases, I agree that this isn't a big deal anymore, but couldn't you just create and push the corresponding tags?

**Comment by cgwalters** [comment]
Ultimately due to the way crates.io works, the crates.io source is canonical.  Personally if I was maintaining this part of crates.io/cargo I'd at least strongly encourage that sources come from a git tag and the client sends a tag+expected sha1, rather than being published client side.  But I think they wanted more repo/VCS independence.

I pushed tags for 0.1.[34] but it looks like I messed up 0.1.2 by not pushing this commit: https://docs.rs/crate/openat-ext/0.1.2/source/.cargo_vcs_info.json

Calling that good enough since from now on I'll treat this more formally because this crate is actually used by other projects we care about.   (At the time it was mostly just a side dep of rpm-ostree, not really formally maintained separately)
